apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: default
  labels:
    app: nodejs
    owner: valerii-vasianovych
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer